name: Build

on:
  pull_request:
    branches:
      - 'master'

jobs:
  run_build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.events.inputs.branch || github.ref }}

      - name: Install maven
        uses: s4u/setup-maven-action@v1.14.0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn clean x
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1